dataset_name: air_quality
format: csv
source_path: data/raw/air_quality/hourly_88101_2024.csv
bronze_table: bronze_air_quality
silver_table: silver_air_quality_hourly
primary_key:
  - State Code
  - County Code
  - Site Num
  - Parameter Code
  - POC
  - Date Local
  - Time Local

timestamp_columns:
  event_timestamp:
    - Date Local
    - Time Local

column_mapping:
  State Code: state_code
  County Code: county_code
  Site Num: site_num
  Parameter Code: parameter_code
  POC: poc
  Latitude: latitude
  Longitude: longitude
  Parameter Name: parameter_name
  Date Local: date_local
  Time Local: time_local
  Sample Measurement: sample_measurement
  Units of Measure: units_of_measure
  State Name: state_name
  County Name: county_name

partition_columns:
  - event_year
  - event_month
